### ISSUE TITLE
to_lab

### ISSUE THREAD

**Issue by Amr-Navy** [nasa/nos3#11]
How to make to_lab send CCSDS TM transfer frame instead of CCSDS packets?

**Comment by jlucas9** [comment]
Hi Amr,
In order to have `to_lab` sent CCSDSS TM frames some major code additions would be necessary.  It doesn't appear that the standard open source `to` application supports it either at this time.  It can and has certainly been done.  In the most simple implementation, somewhere around [here](https://github.com/nasa/nos3/blob/master/apps/to_lab/fsw/src/to_lab_app.c#L534) a framing function would need called to essentially take the standard Space Packet Protocol (typically referred to as the CCSDS packet) and wrap it inside of a TM frame.  
I hope this helps.  Have a great day!
