### ISSUE TITLE
NOS Engine Server Terminal errors and FSW node

### ISSUE THREAD

**Issue by StefanoSWE** [nasa/nos3#235]
Hello!
I'm a new user of NOS3 and I'd like to have support on the following situation.

Would you mind explaining me why NOS Engine Server Terminal is reporting the following errors?

![nos_eng_server_2](https://github.com/nasa/nos3/assets/153757151/cd222649-2c0e-404c-b023-ec57b0f64a88)

Moreover, why isn't _fsw_ present on every bus but only on some busses? E.g. _fsw_ present on _usart_2_ but not on _usart_1_.

![nos_eng_server_1](https://github.com/nasa/nos3/assets/153757151/c10ee946-0eee-452e-9201-06f61ba1e668)

I'm using the main branch.

Thank you so much for your support.

**Comment by jlucas9** [comment]
Hi @StefanoSWE,
I can confirm on the NOS3 main branch (release 1.6.2) I get the following on initial boot:
![image](https://github.com/nasa/nos3/assets/6588622/3827621d-8293-450c-9499-f87543a5cda8)

By default only the sample component is enabled by default. The other components need enabled manually using the OpenC3 command sender which is why only some interfaces show multiple connections:
![image](https://github.com/nasa/nos3/assets/6588622/ecd521cb-aef0-4cfa-8455-b6c3a0d07eb9)

Once that is complete the NOS Engine Server should report the following:
![image](https://github.com/nasa/nos3/assets/6588622/824ca18c-8723-439a-bacf-9e9dbfbaf0e5)

The errors reported by NOS Engine will hopefully be resolved in the next update to Engine, but can be safely ignored for now. Please post any other questions you have and I'll try to get back to you quickly now that I've returned from a long holiday.

**Comment by jlucas9** [comment]
Closing for now, please reopen if more questions arise!
