### ISSUE TITLE
Accessing NOS3_Indv_CLA.pdf link results in "Invalid PDF" error.

### ISSUE THREAD

**Issue by bjkowalski** [nasa/nos3#257]
Accessing the PDF file "NOS3_Indv_CLA.pdf" from the [link](https://github.com/nasa/nos3/blob/dev/doc/NOS3_Indv_CLA.pdf) in README.md under the **Contributions** heading, in the "dev" tree, results in an "Invalid PDF" - "Error rendering embedded code" error.

See attached screenshot.

![Screenshot from 2024-02-23 08-20-21](https://github.com/nasa/nos3/assets/42647415/f4ae33c3-7d6c-4ffb-9faa-9cd6d01b7ffa)

Accessing the file directly, using the browser in the native OS, correctly renders the PDF.

GitHub does not render PDFs from links.  There are workarounds but changing the link to just a file reference in the source tree might avoid others from reporting this as an issue.

**Comment by szemerick** [comment]
Changed the link to point directly to the NASA form for easy downloading.  I edited the text so that it reads:

If you would like to contribute to the repository, please complete this [NASA Form](https://github.com/nasa/nos3/files/14578604/NOS3_Invd_CLA.pdf) and submit it to [gsfc-softwarerequest@mail.nasa.gov](mailto:gsfc-softwarerequest@mail.nasa.gov) with [John.P.Lucas@nasa.gov](mailto:John.P.Lucas@nasa.gov) CC'ed. Next, please create an issue describing the work to be performed noting that you intend to work it, create a related branch, and submit a pull request when ready. When complete, we will review and work to get it integrated.

**Comment by jlucas9** [comment]
Resolved in #280 pull request
