### ISSUE TITLE
Initialization of a new Sim starting from a specific snapshot of the previous one.

### ISSUE THREAD

**Issue by lucapizzuto99** [nasa/nos3#315]
Hello everyone,

I am working with NOS3 to try to initialize a new simulation, that is a new spacecraft, given the orbital conditions and the TM of the originally simulated spacecraft at a time t1.
The idea is, retrieve the orbital position, attitude and TM of the s/c at t1, and use those values to modify the cfg files of another simulation, so that it is like it starts exactly at t1. 
For what I tested so far, the main files appear to be the cfg/InOut/SC_NOS3.txt along with cfg/InOut/Orb_LEO.txt and of course cfg/Sc_full_config.xml. However, the majority of the parameters and config values appear to be constants, and the only way I found to modify the starting orbital position and attitude is to modify the True Anomaly value in the Orb_LEO.txt file. 

My question is: is there another way to accomplish this? And will the TM of the subsystems be updated accordingly, based on the new orbital position?

As a concluding note, it would be nice to have a way to start the sim with all the subsystems enabled. I tried to do this manually but I encountered problems in the fsw during the uart_flash:

`"GENERIC_STAR_TRACKER_CommandDevice - uart_write_port returned -2, expected 9".`

Thank you in advance for your help!

**Comment by doraemox** [comment]
hello, nice to meet you all

**Comment by jlucas9** [comment]
Hi @lucapizzuto99,

I think you're on the right path here and would need to modify the configuration files (primarily the 42 ones) and then launch everything again to resume. Presently we don't have  a means to save the state of the entire environment and launch it again so it would assume you just turned on, like a full power reset of the entire spacecraft, at that location and time and continue. 

If 42 is launched with the new location and time, the rest of the sims will receive updated values and translate those into there own messages as you'd expect, assuming they're configured to reference environmental data that is.  

Starting with all subsystems enabled - that's a great idea. I've created a new branch `nos3#315` to update the relative time sequence (RTS) commands to do this for you. A brief walkthrough of bootup now:
* Spacecraft turns on
* RTS1 (Power on reset) automatically fires
  * Enables data storage (DS) to save telemetry to files
  * Enables debug port so we can view what's going on in the ground software as if we're plugged into the spacecraft
  * Enable RTS3-64 so that they can be used
  * Enables the limit checker (LC) application to perform fault detection and correction, note that none is presently configured
  * Call RTS3
* RTS 3 (Safe mode) 
  * Enable coarse sun sensors (CSS)
  * Enable fine sun sensors (FSS)
  * Enable inertial measurement unit (IMU)
  * Enable magnetometer (MAG)
  * Enable torquers
  * Enable GPS
  * Set ADS to SUNSAFE_MODE

Let me know if you have any other questions!

**Comment by lucapizzuto99** [comment]
Hi @jlucas9,

Thank you so much for your support and quick reply! Starting with all subsystems enabled works as expected. Regarding the initialization of a new sim starting from a previous state, everything works as well, with the exception of the IMU whose linear acceleration values are a bit off, even if the S/C has the same state vector and attitude. I will explore this a bit more.

Thank you again!

**Comment by jlucas9** [comment]
Merged into `dev`! Feel free to re-open or create a new issue as you see anything off!
