### ISSUE TITLE
Anomalies

### ISSUE THREAD

**Issue by UlrichLouw** [nasa/nos3#67]
Good day,

I would like to know if the simulation implements faults (such as the failure of a reaction wheel) based on the statistical probability that a reaction wheel will fail? If the simulation is capable of inducing such anomalies or failures what are all the faults that can occur?

**Comment by jlucas9** [comment]
Closing issue due to age.
Please create a new issue if this problem remains.

Briefly component failures of any kind you are willing to code in can be achieved. The nice thing about NOS3 is that those kind of tests can be performed without (potentially) damaging equipment like you would have to do on a physical setup. There is currently a back-door into the simulators via a terminal interface, new commanding from ground station to come in the future, that allows you to toggle errors for testing.
